/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_connexion (void)
{
  GtkWidget *connexion;
  GtkWidget *fixed1;
  GtkWidget *entryLogin;
  GtkWidget *password;
  GtkWidget *erreur;
  GtkWidget *login;
  GtkWidget *label;
  GtkWidget *mot_de_passe_;
  GtkWidget *btnconnecter;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label18;
  GtkWidget *image21;
  GtkWidget *image20;

  connexion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (connexion), _("Interface de connexion"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (connexion), fixed1);

  entryLogin = gtk_entry_new ();
  gtk_widget_show (entryLogin);
  gtk_fixed_put (GTK_FIXED (fixed1), entryLogin, 184, 96);
  gtk_widget_set_size_request (entryLogin, 160, 27);
  gtk_entry_set_text (GTK_ENTRY (entryLogin), _(" "));
  gtk_entry_set_invisible_char (GTK_ENTRY (entryLogin), 8226);

  password = gtk_entry_new ();
  gtk_widget_show (password);
  gtk_fixed_put (GTK_FIXED (fixed1), password, 184, 136);
  gtk_widget_set_size_request (password, 160, 27);
  gtk_entry_set_visibility (GTK_ENTRY (password), FALSE);

  erreur = gtk_label_new_with_mnemonic (_("<span color=\"\n\nred\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">    </span> "));
  gtk_widget_show (erreur);
  gtk_fixed_put (GTK_FIXED (fixed1), erreur, 136, 176);
  gtk_widget_set_size_request (erreur, 304, 56);
  gtk_label_set_use_markup (GTK_LABEL (erreur), TRUE);
  gtk_misc_set_alignment (GTK_MISC (erreur), 0.58, 0.5);

  login = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  ID :  </span> "));
  gtk_widget_show (login);
  gtk_fixed_put (GTK_FIXED (fixed1), login, 88, 104);
  gtk_widget_set_size_request (login, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (login), TRUE);

  label = gtk_label_new_with_mnemonic (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Connexion  </span></u>"));
  gtk_widget_show (label);
  gtk_fixed_put (GTK_FIXED (fixed1), label, 200, 24);
  gtk_widget_set_size_request (label, 160, 32);
  gtk_label_set_use_markup (GTK_LABEL (label), TRUE);

  mot_de_passe_ = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Mot de Passe :  </span> "));
  gtk_widget_show (mot_de_passe_);
  gtk_fixed_put (GTK_FIXED (fixed1), mot_de_passe_, 32, 136);
  gtk_widget_set_size_request (mot_de_passe_, 152, 24);
  gtk_label_set_use_markup (GTK_LABEL (mot_de_passe_), TRUE);

  btnconnecter = gtk_button_new ();
  gtk_widget_show (btnconnecter);
  gtk_fixed_put (GTK_FIXED (fixed1), btnconnecter, 176, 192);
  gtk_widget_set_size_request (btnconnecter, 168, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (btnconnecter), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("<span color=\"\n\ngreen\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Se Connecter  </span> "));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox6), label18, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  image21 = create_pixmap (connexion, "istockphoto-636444558-612x612.jpg");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed1), image21, 32, 288);
  gtk_widget_set_size_request (image21, 704, 232);

  image20 = create_pixmap (connexion, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed1), image20, 392, 8);
  gtk_widget_set_size_request (image20, 328, 272);

  g_signal_connect ((gpointer) btnconnecter, "clicked",
                    G_CALLBACK (on_btnconnecter_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (mot_de_passe_), password);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (connexion, connexion, "connexion");
  GLADE_HOOKUP_OBJECT (connexion, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (connexion, entryLogin, "entryLogin");
  GLADE_HOOKUP_OBJECT (connexion, password, "password");
  GLADE_HOOKUP_OBJECT (connexion, erreur, "erreur");
  GLADE_HOOKUP_OBJECT (connexion, login, "login");
  GLADE_HOOKUP_OBJECT (connexion, label, "label");
  GLADE_HOOKUP_OBJECT (connexion, mot_de_passe_, "mot_de_passe_");
  GLADE_HOOKUP_OBJECT (connexion, btnconnecter, "btnconnecter");
  GLADE_HOOKUP_OBJECT (connexion, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (connexion, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (connexion, image6, "image6");
  GLADE_HOOKUP_OBJECT (connexion, label18, "label18");
  GLADE_HOOKUP_OBJECT (connexion, image21, "image21");
  GLADE_HOOKUP_OBJECT (connexion, image20, "image20");

  return connexion;
}

GtkWidget*
create_creer_un_compte (void)
{
  GtkWidget *creer_un_compte;
  GtkWidget *fixed2;
  GtkWidget *login;
  GtkWidget *nom;
  GtkWidget *num_tel;
  GtkWidget *adresse;
  GtkWidget *password;
  GtkWidget *prenom;
  GtkObject *moisC_adj;
  GtkWidget *moisC;
  GtkObject *anneeC_adj;
  GtkWidget *anneeC;
  GtkObject *jourC_adj;
  GtkWidget *jourC;
  GtkWidget *label27;
  GtkWidget *femme;
  GSList *femme_group = NULL;
  GtkWidget *homme;
  GtkWidget *tyype;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton1;
  GtkWidget *annuler;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label17;
  GtkWidget *btnValider;
  GtkWidget *valider;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *validation;
  GtkWidget *label65;
  GtkWidget *label67;
  GtkWidget *label7;
  GtkWidget *recevoir_des_notifications_par_SMS_pour_les_disponibilit__s_de_places;
  GtkWidget *recevoir_des_notifications_par_SMS_pour_les_changements_de_r__servations_;
  GtkWidget *label8;
  GtkWidget *type_compte;
  GtkWidget *label6;
  GtkWidget *label64;
  GtkWidget *label66;
  GtkWidget *label5;
  GtkWidget *label68;
  GtkWidget *image23;

  creer_un_compte = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (creer_un_compte), _("creer un compte"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (creer_un_compte), fixed2);

  login = gtk_entry_new ();
  gtk_widget_show (login);
  gtk_fixed_put (GTK_FIXED (fixed2), login, 224, 56);
  gtk_widget_set_size_request (login, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (login), 8226);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed2), nom, 224, 96);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  num_tel = gtk_entry_new ();
  gtk_widget_show (num_tel);
  gtk_fixed_put (GTK_FIXED (fixed2), num_tel, 224, 176);
  gtk_widget_set_size_request (num_tel, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (num_tel), 8226);

  adresse = gtk_entry_new ();
  gtk_widget_show (adresse);
  gtk_fixed_put (GTK_FIXED (fixed2), adresse, 224, 256);
  gtk_widget_set_size_request (adresse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adresse), 8226);
  gtk_entry_set_activates_default (GTK_ENTRY (adresse), TRUE);

  password = gtk_entry_new ();
  gtk_widget_show (password);
  gtk_fixed_put (GTK_FIXED (fixed2), password, 232, 400);
  gtk_widget_set_size_request (password, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (password), 8226);

  prenom = gtk_entry_new ();
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed2), prenom, 224, 136);
  gtk_widget_set_size_request (prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenom), 8226);

  moisC_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  moisC = gtk_spin_button_new (GTK_ADJUSTMENT (moisC_adj), 1, 0);
  gtk_widget_show (moisC);
  gtk_fixed_put (GTK_FIXED (fixed2), moisC, 304, 304);
  gtk_widget_set_size_request (moisC, 60, 27);

  anneeC_adj = gtk_adjustment_new (2024, 1920, 2090, 1, 10, 10);
  anneeC = gtk_spin_button_new (GTK_ADJUSTMENT (anneeC_adj), 1, 0);
  gtk_widget_show (anneeC);
  gtk_fixed_put (GTK_FIXED (fixed2), anneeC, 376, 304);
  gtk_widget_set_size_request (anneeC, 60, 27);

  jourC_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jourC = gtk_spin_button_new (GTK_ADJUSTMENT (jourC_adj), 1, 0);
  gtk_widget_show (jourC);
  gtk_fixed_put (GTK_FIXED (fixed2), jourC, 224, 304);
  gtk_widget_set_size_request (jourC, 60, 27);

  label27 = gtk_label_new ("");
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed2), label27, 64, 352);
  gtk_widget_set_size_request (label27, 49, 17);

  femme = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (femme);
  gtk_fixed_put (GTK_FIXED (fixed2), femme, 376, 224);
  gtk_widget_set_size_request (femme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (femme), femme_group);
  femme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (femme));

  homme = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (homme);
  gtk_fixed_put (GTK_FIXED (fixed2), homme, 240, 224);
  gtk_widget_set_size_request (homme, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (homme), femme_group);
  femme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (homme));

  tyype = gtk_combo_box_entry_new_text ();
  gtk_widget_show (tyype);
  gtk_fixed_put (GTK_FIXED (fixed2), tyype, 232, 440);
  gtk_widget_set_size_request (tyype, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (tyype), _("utilisateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tyype), _("administrateur"));

  checkbutton2 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton2, 672, 376);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  checkbutton1 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton1, 672, 344);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  annuler = gtk_button_new ();
  gtk_widget_show (annuler);
  gtk_fixed_put (GTK_FIXED (fixed2), annuler, 440, 496);
  gtk_widget_set_size_request (annuler, 136, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (annuler), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("<u><span color=\"\n\nred\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Annuler  </span></u>"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox5), label17, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  btnValider = gtk_button_new ();
  gtk_widget_show (btnValider);
  gtk_fixed_put (GTK_FIXED (fixed2), btnValider, 184, 496);
  gtk_widget_set_size_request (btnValider, 128, 40);

  valider = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (valider);
  gtk_container_add (GTK_CONTAINER (btnValider), valider);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (valider), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  validation = gtk_label_new_with_mnemonic (_("<u><span color=\"\n\ngreen\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Valider  </span></u>"));
  gtk_widget_show (validation);
  gtk_box_pack_start (GTK_BOX (hbox4), validation, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (validation), TRUE);

  label65 = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  ID :  </span>"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed2), label65, 80, 64);
  gtk_widget_set_size_request (label65, 41, 17);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);

  label67 = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Pr\303\251nom : </span>"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed2), label67, 56, 144);
  gtk_widget_set_size_request (label67, 104, 16);
  gtk_label_set_use_markup (GTK_LABEL (label67), TRUE);

  label7 = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Date de Naissance :  </span>"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 0, 304);
  gtk_widget_set_size_request (label7, 216, 24);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  recevoir_des_notifications_par_SMS_pour_les_disponibilit__s_de_places = gtk_label_new_with_mnemonic (_("  <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Recevoir des notifications par SMS pour les disponibilit\303\251s de places :  </span>"));
  gtk_widget_show (recevoir_des_notifications_par_SMS_pour_les_disponibilit__s_de_places);
  gtk_fixed_put (GTK_FIXED (fixed2), recevoir_des_notifications_par_SMS_pour_les_disponibilit__s_de_places, 8, 344);
  gtk_widget_set_size_request (recevoir_des_notifications_par_SMS_pour_les_disponibilit__s_de_places, 624, 32);
  gtk_label_set_use_markup (GTK_LABEL (recevoir_des_notifications_par_SMS_pour_les_disponibilit__s_de_places), TRUE);

  recevoir_des_notifications_par_SMS_pour_les_changements_de_r__servations_ = gtk_label_new_with_mnemonic (_("  <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">   Recevoir des notifications par SMS pour les changements de r\303\251servations :  </span>"));
  gtk_widget_show (recevoir_des_notifications_par_SMS_pour_les_changements_de_r__servations_);
  gtk_fixed_put (GTK_FIXED (fixed2), recevoir_des_notifications_par_SMS_pour_les_changements_de_r__servations_, 16, 376);
  gtk_widget_set_size_request (recevoir_des_notifications_par_SMS_pour_les_changements_de_r__servations_, 656, 24);
  gtk_label_set_use_markup (GTK_LABEL (recevoir_des_notifications_par_SMS_pour_les_changements_de_r__servations_), TRUE);

  label8 = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Mot de Passe :  </span>"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 56, 408);
  gtk_widget_set_size_request (label8, 160, 16);
  gtk_label_set_use_markup (GTK_LABEL (label8), TRUE);

  type_compte = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Type du Compte :  </span>"));
  gtk_widget_show (type_compte);
  gtk_fixed_put (GTK_FIXED (fixed2), type_compte, 40, 440);
  gtk_widget_set_size_request (type_compte, 184, 32);
  gtk_label_set_use_markup (GTK_LABEL (type_compte), TRUE);

  label6 = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Adresse :  </span> "));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 80, 264);
  gtk_widget_set_size_request (label6, 88, 16);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  label64 = gtk_label_new_with_mnemonic (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Ajouter un compte  </span></u>"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed2), label64, 128, 8);
  gtk_widget_set_size_request (label64, 352, 32);
  gtk_label_set_use_markup (GTK_LABEL (label64), TRUE);

  label66 = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Nom :  </span>"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed2), label66, 72, 104);
  gtk_widget_set_size_request (label66, 72, 16);
  gtk_label_set_use_markup (GTK_LABEL (label66), TRUE);

  label5 = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Sexe :  </span> "));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 88, 224);
  gtk_widget_set_size_request (label5, 72, 16);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  label68 = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Num\303\251ro de T\303\251l\303\251phone : </span>"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed2), label68, 8, 184);
  gtk_widget_set_size_request (label68, 216, 16);
  gtk_label_set_use_markup (GTK_LABEL (label68), TRUE);

  image23 = create_pixmap (creer_un_compte, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed2), image23, 456, 16);
  gtk_widget_set_size_request (image23, 376, 312);

  g_signal_connect ((gpointer) femme, "toggled",
                    G_CALLBACK (on_femme_toggled),
                    NULL);
  g_signal_connect ((gpointer) homme, "toggled",
                    G_CALLBACK (on_homme_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) annuler, "clicked",
                    G_CALLBACK (on_annuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnValider, "clicked",
                    G_CALLBACK (on_btnValider_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label7), jourC);
  gtk_label_set_mnemonic_widget (GTK_LABEL (recevoir_des_notifications_par_SMS_pour_les_disponibilit__s_de_places), checkbutton1);
  gtk_label_set_mnemonic_widget (GTK_LABEL (recevoir_des_notifications_par_SMS_pour_les_changements_de_r__servations_), checkbutton2);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label5), homme);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (creer_un_compte, creer_un_compte, "creer_un_compte");
  GLADE_HOOKUP_OBJECT (creer_un_compte, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (creer_un_compte, login, "login");
  GLADE_HOOKUP_OBJECT (creer_un_compte, nom, "nom");
  GLADE_HOOKUP_OBJECT (creer_un_compte, num_tel, "num_tel");
  GLADE_HOOKUP_OBJECT (creer_un_compte, adresse, "adresse");
  GLADE_HOOKUP_OBJECT (creer_un_compte, password, "password");
  GLADE_HOOKUP_OBJECT (creer_un_compte, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (creer_un_compte, moisC, "moisC");
  GLADE_HOOKUP_OBJECT (creer_un_compte, anneeC, "anneeC");
  GLADE_HOOKUP_OBJECT (creer_un_compte, jourC, "jourC");
  GLADE_HOOKUP_OBJECT (creer_un_compte, label27, "label27");
  GLADE_HOOKUP_OBJECT (creer_un_compte, femme, "femme");
  GLADE_HOOKUP_OBJECT (creer_un_compte, homme, "homme");
  GLADE_HOOKUP_OBJECT (creer_un_compte, tyype, "tyype");
  GLADE_HOOKUP_OBJECT (creer_un_compte, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (creer_un_compte, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (creer_un_compte, annuler, "annuler");
  GLADE_HOOKUP_OBJECT (creer_un_compte, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (creer_un_compte, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (creer_un_compte, image5, "image5");
  GLADE_HOOKUP_OBJECT (creer_un_compte, label17, "label17");
  GLADE_HOOKUP_OBJECT (creer_un_compte, btnValider, "btnValider");
  GLADE_HOOKUP_OBJECT (creer_un_compte, valider, "valider");
  GLADE_HOOKUP_OBJECT (creer_un_compte, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (creer_un_compte, image4, "image4");
  GLADE_HOOKUP_OBJECT (creer_un_compte, validation, "validation");
  GLADE_HOOKUP_OBJECT (creer_un_compte, label65, "label65");
  GLADE_HOOKUP_OBJECT (creer_un_compte, label67, "label67");
  GLADE_HOOKUP_OBJECT (creer_un_compte, label7, "label7");
  GLADE_HOOKUP_OBJECT (creer_un_compte, recevoir_des_notifications_par_SMS_pour_les_disponibilit__s_de_places, "recevoir_des_notifications_par_SMS_pour_les_disponibilit__s_de_places");
  GLADE_HOOKUP_OBJECT (creer_un_compte, recevoir_des_notifications_par_SMS_pour_les_changements_de_r__servations_, "recevoir_des_notifications_par_SMS_pour_les_changements_de_r__servations_");
  GLADE_HOOKUP_OBJECT (creer_un_compte, label8, "label8");
  GLADE_HOOKUP_OBJECT (creer_un_compte, type_compte, "type_compte");
  GLADE_HOOKUP_OBJECT (creer_un_compte, label6, "label6");
  GLADE_HOOKUP_OBJECT (creer_un_compte, label64, "label64");
  GLADE_HOOKUP_OBJECT (creer_un_compte, label66, "label66");
  GLADE_HOOKUP_OBJECT (creer_un_compte, label5, "label5");
  GLADE_HOOKUP_OBJECT (creer_un_compte, label68, "label68");
  GLADE_HOOKUP_OBJECT (creer_un_compte, image23, "image23");

  return creer_un_compte;
}

GtkWidget*
create_Liste_des_citoyens (void)
{
  GtkWidget *Liste_des_citoyens;
  GtkWidget *fixed4;
  GtkWidget *treeview1;
  GtkWidget *afficher_la_facture_mensuelle;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label70;
  GtkWidget *ajouter_un_compte_;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label30;
  GtkWidget *modifier_un_compte;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label31;
  GtkWidget *supprimer_citoyen;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label32;
  GtkWidget *afficherC;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label69;
  GtkWidget *liste_des_citoyens;
  GtkWidget *image22;
  GtkWidget *acceuil_cit;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label33;

  Liste_des_citoyens = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Liste_des_citoyens), _("Liste des citoyens"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Liste_des_citoyens), fixed4);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview1, 16, 64);
  gtk_widget_set_size_request (treeview1, 792, 304);

  afficher_la_facture_mensuelle = gtk_button_new ();
  gtk_widget_show (afficher_la_facture_mensuelle);
  gtk_fixed_put (GTK_FIXED (fixed4), afficher_la_facture_mensuelle, 328, 456);
  gtk_widget_set_size_request (afficher_la_facture_mensuelle, 288, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (afficher_la_facture_mensuelle), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-directory", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label70 = gtk_label_new_with_mnemonic (_("<span color=\"\n\ngreen\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Afficher la facture mensuelle </span> "));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (hbox16), label70, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label70), TRUE);

  ajouter_un_compte_ = gtk_button_new ();
  gtk_widget_show (ajouter_un_compte_);
  gtk_fixed_put (GTK_FIXED (fixed4), ajouter_un_compte_, 40, 392);
  gtk_widget_set_size_request (ajouter_un_compte_, 208, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (ajouter_un_compte_), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Ajouter un Compte </span> "));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox8), label30, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  modifier_un_compte = gtk_button_new ();
  gtk_widget_show (modifier_un_compte);
  gtk_fixed_put (GTK_FIXED (fixed4), modifier_un_compte, 272, 392);
  gtk_widget_set_size_request (modifier_un_compte, 144, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (modifier_un_compte), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Modifier  </span> "));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox9), label31, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  supprimer_citoyen = gtk_button_new ();
  gtk_widget_show (supprimer_citoyen);
  gtk_fixed_put (GTK_FIXED (fixed4), supprimer_citoyen, 432, 392);
  gtk_widget_set_size_request (supprimer_citoyen, 176, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (supprimer_citoyen), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("<span color=\"\n\nred\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Supprimer  </span> "));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox10), label32, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  afficherC = gtk_button_new ();
  gtk_widget_show (afficherC);
  gtk_fixed_put (GTK_FIXED (fixed4), afficherC, 624, 392);
  gtk_widget_set_size_request (afficherC, 280, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (afficherC), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("<span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Afficher touts les Comptes  </span> "));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox15), label69, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label69), TRUE);

  liste_des_citoyens = gtk_label_new_with_mnemonic (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Liste des Citoyens  </span></u>"));
  gtk_widget_show (liste_des_citoyens);
  gtk_fixed_put (GTK_FIXED (fixed4), liste_des_citoyens, 248, 16);
  gtk_widget_set_size_request (liste_des_citoyens, 312, 40);
  gtk_label_set_use_markup (GTK_LABEL (liste_des_citoyens), TRUE);

  image22 = create_pixmap (Liste_des_citoyens, "gps.jpg");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed4), image22, 816, 8);
  gtk_widget_set_size_request (image22, 256, 384);

  acceuil_cit = gtk_button_new ();
  gtk_widget_show (acceuil_cit);
  gtk_fixed_put (GTK_FIXED (fixed4), acceuil_cit, 640, 8);
  gtk_widget_set_size_request (acceuil_cit, 80, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (acceuil_cit), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("acceuil"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox11), label33, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ajouter_un_compte_, "clicked",
                    G_CALLBACK (on_ajouter_un_compte__clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_un_compte, "clicked",
                    G_CALLBACK (on_modifier_un_compte_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_citoyen, "clicked",
                    G_CALLBACK (on_supprimer_citoyen_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficherC, "clicked",
                    G_CALLBACK (on_afficherC_clicked),
                    NULL);
  g_signal_connect ((gpointer) acceuil_cit, "clicked",
                    G_CALLBACK (on_acceuil_cit_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Liste_des_citoyens, Liste_des_citoyens, "Liste_des_citoyens");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, afficher_la_facture_mensuelle, "afficher_la_facture_mensuelle");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, image16, "image16");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, label70, "label70");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, ajouter_un_compte_, "ajouter_un_compte_");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, image8, "image8");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, label30, "label30");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, modifier_un_compte, "modifier_un_compte");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, image9, "image9");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, label31, "label31");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, supprimer_citoyen, "supprimer_citoyen");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, image10, "image10");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, label32, "label32");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, afficherC, "afficherC");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, image15, "image15");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, label69, "label69");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, liste_des_citoyens, "liste_des_citoyens");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, image22, "image22");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, acceuil_cit, "acceuil_cit");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, image11, "image11");
  GLADE_HOOKUP_OBJECT (Liste_des_citoyens, label33, "label33");

  return Liste_des_citoyens;
}

GtkWidget*
create_modification (void)
{
  GtkWidget *modification;
  GtkWidget *fixed5;
  GtkWidget *idmodif;
  GtkWidget *nommodif;
  GtkWidget *prenommodif;
  GtkWidget *numtelmodif;
  GtkObject *spinjour_adj;
  GtkWidget *spinjour;
  GtkObject *spinmois_adj;
  GtkWidget *spinmois;
  GtkObject *spinannee_adj;
  GtkWidget *spinannee;
  GtkWidget *adressemodif;
  GtkWidget *mdpmodif;
  GtkWidget *label47;
  GtkWidget *label53;
  GtkWidget *label49;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *checkbutton4;
  GtkWidget *label56;
  GtkWidget *typemodif;
  GtkWidget *label57;
  GtkWidget *label61;
  GtkWidget *f;
  GSList *f_group = NULL;
  GtkWidget *h;
  GtkWidget *label52;
  GtkWidget *valider_modification;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label62;
  GtkWidget *annuler_modification;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label63;
  GtkWidget *label48;
  GtkWidget *label55;
  GtkWidget *label54;
  GtkWidget *recher;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label59;
  GtkWidget *checkbutton3;
  GtkWidget *image24;

  modification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modification), _("modifier un compte"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (modification), fixed5);

  idmodif = gtk_entry_new ();
  gtk_widget_show (idmodif);
  gtk_fixed_put (GTK_FIXED (fixed5), idmodif, 472, 48);
  gtk_widget_set_size_request (idmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (idmodif), 8226);

  nommodif = gtk_entry_new ();
  gtk_widget_show (nommodif);
  gtk_fixed_put (GTK_FIXED (fixed5), nommodif, 256, 88);
  gtk_widget_set_size_request (nommodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nommodif), 8226);

  prenommodif = gtk_entry_new ();
  gtk_widget_show (prenommodif);
  gtk_fixed_put (GTK_FIXED (fixed5), prenommodif, 256, 128);
  gtk_widget_set_size_request (prenommodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenommodif), 8226);

  numtelmodif = gtk_entry_new ();
  gtk_widget_show (numtelmodif);
  gtk_fixed_put (GTK_FIXED (fixed5), numtelmodif, 256, 168);
  gtk_widget_set_size_request (numtelmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (numtelmodif), 8226);

  spinjour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinjour = gtk_spin_button_new (GTK_ADJUSTMENT (spinjour_adj), 1, 0);
  gtk_widget_show (spinjour);
  gtk_fixed_put (GTK_FIXED (fixed5), spinjour, 256, 296);
  gtk_widget_set_size_request (spinjour, 60, 27);

  spinmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinmois = gtk_spin_button_new (GTK_ADJUSTMENT (spinmois_adj), 1, 0);
  gtk_widget_show (spinmois);
  gtk_fixed_put (GTK_FIXED (fixed5), spinmois, 328, 296);
  gtk_widget_set_size_request (spinmois, 60, 27);

  spinannee_adj = gtk_adjustment_new (2024, 1920, 2090, 1, 10, 10);
  spinannee = gtk_spin_button_new (GTK_ADJUSTMENT (spinannee_adj), 1, 0);
  gtk_widget_show (spinannee);
  gtk_fixed_put (GTK_FIXED (fixed5), spinannee, 400, 296);
  gtk_widget_set_size_request (spinannee, 60, 27);

  adressemodif = gtk_entry_new ();
  gtk_widget_show (adressemodif);
  gtk_fixed_put (GTK_FIXED (fixed5), adressemodif, 256, 248);
  gtk_widget_set_size_request (adressemodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adressemodif), 8226);

  mdpmodif = gtk_entry_new ();
  gtk_widget_show (mdpmodif);
  gtk_fixed_put (GTK_FIXED (fixed5), mdpmodif, 256, 400);
  gtk_widget_set_size_request (mdpmodif, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (mdpmodif), 8226);

  label47 = gtk_label_new_with_mnemonic (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Modifier un compte </span></u>"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed5), label47, 176, 16);
  gtk_widget_set_size_request (label47, 288, 24);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  label53 = gtk_label_new_with_mnemonic (_(" <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">   Adresse :  </span> "));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed5), label53, 64, 256);
  gtk_widget_set_size_request (label53, 88, 16);
  gtk_label_set_use_markup (GTK_LABEL (label53), TRUE);

  label49 = gtk_label_new_with_mnemonic (_(" <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">   Nom :  </span> "));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed5), label49, 80, 96);
  gtk_widget_set_size_request (label49, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  label50 = gtk_label_new_with_mnemonic (_(" <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">   Pr\303\251nom : </span> "));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed5), label50, 72, 136);
  gtk_widget_set_size_request (label50, 96, 16);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  label51 = gtk_label_new_with_mnemonic (_(" <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">   Num\303\251ro de T\303\251l\303\251phone : </span> "));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed5), label51, 16, 176);
  gtk_widget_set_size_request (label51, 216, 16);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  checkbutton4 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton4, 704, 368);
  gtk_widget_set_size_request (checkbutton4, 118, 24);

  label56 = gtk_label_new_with_mnemonic (_(" <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">   Recevoir des notifications par SMS pour les changements de r\303\251servations :  </span>    "));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed5), label56, 24, 368);
  gtk_widget_set_size_request (label56, 664, 24);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  typemodif = gtk_combo_box_entry_new_text ();
  gtk_widget_show (typemodif);
  gtk_fixed_put (GTK_FIXED (fixed5), typemodif, 256, 448);
  gtk_widget_set_size_request (typemodif, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (typemodif), _("utilisateur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (typemodif), _("administrateur"));

  label57 = gtk_label_new_with_mnemonic (_(" <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Mot de Passe :  </span>"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed5), label57, 32, 400);
  gtk_widget_set_size_request (label57, 176, 24);
  gtk_label_set_use_markup (GTK_LABEL (label57), TRUE);

  label61 = gtk_label_new_with_mnemonic (_(" <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\"> Type du Compte :  </span>"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed5), label61, 56, 448);
  gtk_widget_set_size_request (label61, 168, 24);
  gtk_label_set_use_markup (GTK_LABEL (label61), TRUE);

  f = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (f);
  gtk_fixed_put (GTK_FIXED (fixed5), f, 368, 216);
  gtk_widget_set_size_request (f, 192, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (f), f_group);
  f_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (f));

  h = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (h);
  gtk_fixed_put (GTK_FIXED (fixed5), h, 232, 216);
  gtk_widget_set_size_request (h, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (h), f_group);
  f_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (h));

  label52 = gtk_label_new_with_mnemonic (_(" <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">   Sexe : </span> "));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed5), label52, 80, 216);
  gtk_widget_set_size_request (label52, 88, 16);
  gtk_label_set_use_markup (GTK_LABEL (label52), TRUE);

  valider_modification = gtk_button_new ();
  gtk_widget_show (valider_modification);
  gtk_fixed_put (GTK_FIXED (fixed5), valider_modification, 96, 496);
  gtk_widget_set_size_request (valider_modification, 136, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (valider_modification), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("<u><span color=\"\n\ngreen\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Valider  </span></u>"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox13), label62, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label62), TRUE);

  annuler_modification = gtk_button_new ();
  gtk_widget_show (annuler_modification);
  gtk_fixed_put (GTK_FIXED (fixed5), annuler_modification, 440, 496);
  gtk_widget_set_size_request (annuler_modification, 128, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (annuler_modification), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label63 = gtk_label_new_with_mnemonic (_("<u><span color=\"\n\nred\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">  Annuler  </span></u>"));
  gtk_widget_show (label63);
  gtk_box_pack_start (GTK_BOX (hbox14), label63, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label63), TRUE);

  label48 = gtk_label_new_with_mnemonic (_(" <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">   Ecrivez l'ID du compte que vous voulez modifier :  </span>  "));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed5), label48, 8, 48);
  gtk_widget_set_size_request (label48, 448, 24);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  label55 = gtk_label_new_with_mnemonic (_(" <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">    Recevoir des notifications par SMS pour les disponibilit\303\251s de places : </span>     "));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed5), label55, 16, 336);
  gtk_widget_set_size_request (label55, 632, 32);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);

  label54 = gtk_label_new_with_mnemonic (_(" <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">   Date de Naissance :  </span> "));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed5), label54, 32, 296);
  gtk_widget_set_size_request (label54, 192, 24);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);

  recher = gtk_button_new ();
  gtk_widget_show (recher);
  gtk_fixed_put (GTK_FIXED (fixed5), recher, 648, 48);
  gtk_widget_set_size_request (recher, 168, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (recher), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label59 = gtk_label_new_with_mnemonic (_(" <span color=\"\n\nblack\"font-weight=\"Bold\"  font=\"Verdana\" size=\"medium\">   RECHERCHER </span> "));
  gtk_widget_show (label59);
  gtk_box_pack_start (GTK_BOX (hbox12), label59, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label59), TRUE);

  checkbutton3 = gtk_check_button_new_with_mnemonic ("");
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed5), checkbutton3, 704, 344);
  gtk_widget_set_size_request (checkbutton3, 80, 24);

  image24 = create_pixmap (modification, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image24);
  gtk_fixed_put (GTK_FIXED (fixed5), image24, 456, 80);
  gtk_widget_set_size_request (image24, 472, 264);

  g_signal_connect ((gpointer) checkbutton4, "toggled",
                    G_CALLBACK (on_checkbutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) f, "toggled",
                    G_CALLBACK (on_f_toggled),
                    NULL);
  g_signal_connect ((gpointer) h, "toggled",
                    G_CALLBACK (on_h_toggled),
                    NULL);
  g_signal_connect ((gpointer) valider_modification, "clicked",
                    G_CALLBACK (on_valider_modification_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler_modification, "clicked",
                    G_CALLBACK (on_annuler_modification_clicked),
                    NULL);
  g_signal_connect ((gpointer) recher, "clicked",
                    G_CALLBACK (on_recher_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3, "toggled",
                    G_CALLBACK (on_checkbutton3_toggled),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label56), checkbutton4);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label57), mdpmodif);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label52), h);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label48), idmodif);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label55), checkbutton3);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label54), spinjour);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modification, modification, "modification");
  GLADE_HOOKUP_OBJECT (modification, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (modification, idmodif, "idmodif");
  GLADE_HOOKUP_OBJECT (modification, nommodif, "nommodif");
  GLADE_HOOKUP_OBJECT (modification, prenommodif, "prenommodif");
  GLADE_HOOKUP_OBJECT (modification, numtelmodif, "numtelmodif");
  GLADE_HOOKUP_OBJECT (modification, spinjour, "spinjour");
  GLADE_HOOKUP_OBJECT (modification, spinmois, "spinmois");
  GLADE_HOOKUP_OBJECT (modification, spinannee, "spinannee");
  GLADE_HOOKUP_OBJECT (modification, adressemodif, "adressemodif");
  GLADE_HOOKUP_OBJECT (modification, mdpmodif, "mdpmodif");
  GLADE_HOOKUP_OBJECT (modification, label47, "label47");
  GLADE_HOOKUP_OBJECT (modification, label53, "label53");
  GLADE_HOOKUP_OBJECT (modification, label49, "label49");
  GLADE_HOOKUP_OBJECT (modification, label50, "label50");
  GLADE_HOOKUP_OBJECT (modification, label51, "label51");
  GLADE_HOOKUP_OBJECT (modification, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (modification, label56, "label56");
  GLADE_HOOKUP_OBJECT (modification, typemodif, "typemodif");
  GLADE_HOOKUP_OBJECT (modification, label57, "label57");
  GLADE_HOOKUP_OBJECT (modification, label61, "label61");
  GLADE_HOOKUP_OBJECT (modification, f, "f");
  GLADE_HOOKUP_OBJECT (modification, h, "h");
  GLADE_HOOKUP_OBJECT (modification, label52, "label52");
  GLADE_HOOKUP_OBJECT (modification, valider_modification, "valider_modification");
  GLADE_HOOKUP_OBJECT (modification, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (modification, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (modification, image13, "image13");
  GLADE_HOOKUP_OBJECT (modification, label62, "label62");
  GLADE_HOOKUP_OBJECT (modification, annuler_modification, "annuler_modification");
  GLADE_HOOKUP_OBJECT (modification, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (modification, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (modification, image14, "image14");
  GLADE_HOOKUP_OBJECT (modification, label63, "label63");
  GLADE_HOOKUP_OBJECT (modification, label48, "label48");
  GLADE_HOOKUP_OBJECT (modification, label55, "label55");
  GLADE_HOOKUP_OBJECT (modification, label54, "label54");
  GLADE_HOOKUP_OBJECT (modification, recher, "recher");
  GLADE_HOOKUP_OBJECT (modification, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (modification, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (modification, image12, "image12");
  GLADE_HOOKUP_OBJECT (modification, label59, "label59");
  GLADE_HOOKUP_OBJECT (modification, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (modification, image24, "image24");

  return modification;
}

