/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_connexion (void);
GtkWidget* create_creer_un_compte (void);
GtkWidget* create_Liste_des_citoyens (void);
GtkWidget* create_modification (void);
